version: '3.8'
services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra_nyc
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - cassandra_data:/var/lib/cassandra
volumes:
  cassandra_data: 